"""make_notebook.py — generates unified_runpod_inference.ipynb"""
import json, pathlib

def code(lines):
    return {"cell_type":"code","metadata":{},"outputs":[],"execution_count":None,"source":lines}
def md(text):
    return {"cell_type":"markdown","metadata":{},"source":[text]}

cells = [

md("# Moshi → Bridge → AvatarForcing Unified Streaming Pipeline\n\n**Real-Time Speech-to-Avatar on RunPod GPU**\n\n```\nUser Audio → Moshi LM (tokens @12.5Hz) → Bridge (wav2vec features @25Hz) → AvatarForcing (video @25fps)\n```"),

code([
"import torch, sys\n",
"print('PyTorch:', torch.__version__)\n",
"print('CUDA:', torch.cuda.is_available())\n",
"for i in range(torch.cuda.device_count()):\n",
"    p = torch.cuda.get_device_properties(i)\n",
"    total_gb = p.total_memory / 1_000_000_000\n",
"    print(f'  GPU {i}: {p.name} | {total_gb:.1f} GB')\n",
"print('Python:', sys.version.split()[0])\n",
]),

code([
"import subprocess, sys\n",
"# System deps\n",
"subprocess.run('apt-get update -qq && apt-get install -y -qq ffmpeg libsndfile1'.split('&&')[0].split(), check=True, capture_output=True)\n",
"subprocess.run(['apt-get','install','-y','-qq','ffmpeg','libsndfile1','git'], check=True, capture_output=True)\n",
"print('System deps OK')\n",
]),

code([
"import subprocess, sys\n",
"pkgs = [\n",
"    'moshi==0.2.4', 'sphn>=0.1.4', 'sentencepiece>=0.1.99',\n",
"    'transformers==4.41.2', 'accelerate==0.31.0', 'diffusers==0.30.0',\n",
"    'peft==0.13.0', 'ftfy', 'easydict', 'safetensors>=0.4.0',\n",
"    'huggingface_hub>=0.23.0', 'omegaconf>=2.3.0', 'einops>=0.7.0',\n",
"    'soundfile>=0.12.1', 'pyyaml>=6.0', 'pillow>=10.0', 'decord>=0.6.0',\n",
"    'websockets>=12.0', 'lmdb>=1.4.0', 'pandas>=2.0',\n",
"    'opencv-python-headless>=4.8', 'pyworld>=0.3.4', 'tqdm>=4.66',\n",
"    'ipywidgets>=8.0',\n",
"]\n",
"subprocess.run([sys.executable,'-m','pip','install','-q'] + pkgs, check=True)\n",
"print('Python packages installed')\n",
]),

code([
"# Remove broken flash-attn to force PyTorch SDPA fallback (much more stable)\n",
"import subprocess, sys\n",
"subprocess.run([sys.executable,'-m','pip','uninstall','-y','flash-attn', 'xformers'], check=False, capture_output=True)\n",
"print('Removed flash-attn/xformers to use native PyTorch SDPA instead (avoids C++ ABI crashes)')\n",
]),

code([
"import sys\n",
"from pathlib import Path\n",
"\n",
"# ─── CONFIGURE THESE ─────────────────────────────────────────────────────────\n",
"WORKSPACE    = Path('/workspace')\n",
"BRIDGE_ROOT  = WORKSPACE / 'Moshi-AvatarForcing-bridge'\n",
"MOSHI_ROOT   = BRIDGE_ROOT / 'moshi-inference'\n",
"AF_ROOT      = BRIDGE_ROOT / 'AvatarForcing-inference'\n",
"BRIDGE_MOD   = BRIDGE_ROOT / 'bridge_module'\n",
"UNIFIED      = BRIDGE_ROOT / 'unified_pipeline'\n",
"WAN_DIR      = AF_ROOT / 'wan_models'\n",
"BRIDGE_CKPT  = BRIDGE_ROOT / 'checkpoints' / 'bridge_best.pt'\n",
"BRIDGE_CFG   = BRIDGE_MOD / 'config.yaml'\n",
"AF_CKPT      = AF_ROOT / 'checkpoints' / 'model.pt'   # Update this if your checkpoint name differs\n",
"AF_CFG       = AF_ROOT / 'configs' / 'avatarforcing.yaml'\n",
"# ─────────────────────────────────────────────────────────────────────────────\n",
"\n",
"for p in [str(BRIDGE_ROOT), str(MOSHI_ROOT), str(AF_ROOT), str(BRIDGE_MOD)]:\n",
"    if p not in sys.path:\n",
"        sys.path.insert(0, p)\n",
"\n",
"print('Paths set up:')\n",
"for p in [BRIDGE_ROOT, MOSHI_ROOT, AF_ROOT, BRIDGE_MOD]:\n",
"    print(' ', p, '✓' if p.exists() else '✗ MISSING')\n",
]),

code([
"from huggingface_hub import snapshot_download\n",
"\n",
"WAN_DIR.mkdir(parents=True, exist_ok=True)\n",
"\n",
"print('Downloading Wan2.1-T2V-1.3B (large, ~14GB)...')\n",
"snapshot_download(\n",
"    repo_id='Wan-AI/Wan2.1-T2V-1.3B',\n",
"    local_dir=str(WAN_DIR / 'Wan2.1-T2V-1.3B'),\n",
"    ignore_patterns=['*.md'],\n",
")\n",
"print('Wan2.1 OK')\n",
"\n",
"print('Downloading wav2vec2-base-960h...')\n",
"snapshot_download(\n",
"    repo_id='facebook/wav2vec2-base-960h',\n",
"    local_dir=str(WAN_DIR / 'wav2vec2-base-960h'),\n",
")\n",
"print('wav2vec2 OK')\n",
]),

code([
"# Upload reference image and input audio\n",
"import ipywidgets as widgets\n",
"from IPython.display import display\n",
"\n",
"upload_img = widgets.FileUpload(accept='image/*', multiple=False, description='Portrait Image')\n",
"upload_aud = widgets.FileUpload(accept='audio/*', multiple=False, description='Input Audio')\n",
"display(widgets.VBox([upload_img, upload_aud]))\n",
"print('Upload your files above, then run the next cell.')\n",
]),

code([
"from pathlib import Path\n",
"\n",
"UPLOADS = BRIDGE_ROOT / 'uploads'\n",
"UPLOADS.mkdir(exist_ok=True)\n",
"\n",
"# Save image\n",
"if upload_img.value:\n",
"    fname, data = next(iter(upload_img.value.items()))\n",
"    IMAGE_PATH = str(UPLOADS / fname)\n",
"    Path(IMAGE_PATH).write_bytes(data['content'])\n",
"    print('Image saved:', IMAGE_PATH)\n",
"else:\n",
"    IMAGE_PATH = '/path/to/your/portrait.jpg'  # set manually if not using widget\n",
"    print('WARN: no upload — set IMAGE_PATH manually')\n",
"\n",
"# Save audio\n",
"if upload_aud.value:\n",
"    fname, data = next(iter(upload_aud.value.items()))\n",
"    AUDIO_PATH = str(UPLOADS / fname)\n",
"    Path(AUDIO_PATH).write_bytes(data['content'])\n",
"    print('Audio saved:', AUDIO_PATH)\n",
"else:\n",
"    AUDIO_PATH = '/path/to/your/audio.wav'  # set manually\n",
"    print('WARN: no upload — set AUDIO_PATH manually')\n",
"\n",
"OUTPUT_PATH = str(BRIDGE_ROOT / 'output' / 'avatar_output.mp4')\n",
"Path(OUTPUT_PATH).parent.mkdir(exist_ok=True)\n",
"print('Output path:', OUTPUT_PATH)\n",
]),

code([
"import logging, torch\n",
"logging.basicConfig(level=logging.INFO,\n",
"    format='%(asctime)s [%(levelname)s] %(name)s - %(message)s')\n",
"\n",
"from unified_pipeline.config import (\n",
"    PipelineConfig, MoshiConfig, BridgeConfig, AvatarForcingConfig,\n",
"    DEFAULT_AVATAR_PROMPT\n",
")\n",
"\n",
"cfg = PipelineConfig(\n",
"    moshi=MoshiConfig(\n",
"        hf_repo='kyutai/moshiko-pytorch-bf16',\n",
"        device='cuda',\n",
"        dtype=torch.bfloat16,\n",
"        use_sampling=True,\n",
"        temp=0.8, temp_text=0.7, top_k=250,\n",
"    ),\n",
"    bridge=BridgeConfig(\n",
"        checkpoint_path=str(BRIDGE_CKPT),\n",
"        config_path=str(BRIDGE_CFG),\n",
"        device='cuda',\n",
"        dtype=torch.bfloat16,\n",
"        chunk_tokens=4,      # 4 moshi frames = 320ms per bridge chunk\n",
"        upsample_factor=2,   # 12.5Hz tokens x2 = 25Hz audio features\n",
"        use_kv_cache=True,\n",
"        use_projection=True, # project bridge 768-dim -> 9984-dim\n",
"        wav2vec_num_layers=13,\n",
"    ),\n",
"    avatar=AvatarForcingConfig(\n",
"        avatarforcing_root=str(AF_ROOT),\n",
"        config_path=str(AF_CFG),\n",
"        checkpoint_path=str(AF_CKPT),\n",
"        device='cuda',\n",
"        dtype=torch.bfloat16,\n",
"        num_output_frames=21,\n",
"        fps=25,\n",
"        prompt=DEFAULT_AVATAR_PROMPT,\n",
"        seed=42,\n",
"    ),\n",
"    token_queue_maxsize=128,\n",
"    feature_queue_maxsize=64,\n",
"    frame_queue_maxsize=32,\n",
")\n",
"\n",
"print('Config OK')\n",
"print('Prompt:', cfg.avatar.prompt[:100], '...')\n",
]),

code([
"import gc, torch\n",
"torch.cuda.empty_cache(); gc.collect()\n",
"\n",
"from unified_pipeline.model_loader import load_all_models\n",
"\n",
"print('Loading all models (first run downloads ~20GB, may take 10-15 min)...')\n",
"models = load_all_models(cfg)\n",
"\n",
"mimi       = models['mimi']\n",
"lm_gen     = models['lm_gen']\n",
"bridge     = models['bridge']\n",
"projection = models['projection']\n",
"av_pipe    = models['pipeline']\n",
"\n",
"alloc = torch.cuda.memory_allocated() / 1e9\n",
"res   = torch.cuda.memory_reserved()  / 1e9\n",
"print(f'\\nAll models loaded!')\n",
"print(f'VRAM: {alloc:.2f} GB allocated / {res:.2f} GB reserved')\n",
]),

code([
"from unified_pipeline.async_pipeline import UnifiedPipeline\n",
"\n",
"unified = UnifiedPipeline(cfg, models)\n",
"unified.setup_reference_image(IMAGE_PATH)\n",
"print('Pipeline ready - reference image encoded')\n",
]),

code([
"import sphn, torch\n",
"\n",
"print('Loading audio:', AUDIO_PATH)\n",
"in_pcms, _ = sphn.read(AUDIO_PATH, sample_rate=mimi.sample_rate)\n",
"audio_tensor = torch.from_numpy(in_pcms).cuda()[None, 0:1]  # [1,1,N]\n",
"duration_s = audio_tensor.shape[-1] / mimi.sample_rate\n",
"n_samples  = audio_tensor.shape[-1]\n",
"print(f'Audio: {duration_s:.2f}s | {n_samples} samples @ {mimi.sample_rate}Hz')\n",
]),

code([
"import asyncio, time\n",
"\n",
"print('Starting streaming pipeline...')\n",
"print(f'Output: {OUTPUT_PATH}')\n",
"\n",
"t0 = time.monotonic()\n",
"\n",
"async def run():\n",
"    return await unified.run_to_video(\n",
"        audio_tensor,\n",
"        output_path=OUTPUT_PATH,\n",
"        fps=cfg.avatar.fps,\n",
"        max_blocks=64,\n",
"    )\n",
"\n",
"# Run async pipeline natively in Jupyter\n",
"out_path = await run()\n",
"elapsed = time.monotonic() - t0\n",
"n_frames = unified.avatar_generator._generated_frames\n",
"fps_achieved = n_frames / max(elapsed, 0.01)\n",
"print(f'Done in {elapsed:.1f}s | {n_frames} frames | {fps_achieved:.1f} fps achieved')\n",
"print('Output:', out_path)\n",
]),

code([
"from IPython.display import Video, display\n",
"display(Video(OUTPUT_PATH, embed=True, width=640))\n",
]),

code([
"# Streaming frame-by-frame preview (first 5 frames)\n",
"import asyncio\n",
"from PIL import Image as PILImage\n",
"from IPython.display import display as ipy_display\n",
"import io\n",
"\n",
"print('Streaming preview (first 5 frames):')\n",
"\n",
"async def preview_frames():\n",
"    count = 0\n",
"    async for frame in unified.run(audio_tensor, max_blocks=4):\n",
"        if count >= 5: break\n",
"        pil = PILImage.fromarray(frame.pixels.numpy())\n",
"        print(f'Frame {frame.frame_idx} | latency={frame.latency_ms:.0f}ms')\n",
"        ipy_display(pil)\n",
"        count += 1\n",
"\n",
"await preview_frames()\n",
]),

code([
"# Latency benchmark\n",
"import asyncio\n",
"\n",
"print('Running 5s latency benchmark...')\n",
"\n",
"async def bench():\n",
"    return await unified.benchmark_latency(audio_seconds=5.0)\n",
"\n",
"timings = await bench()\n",
"print('Latency results:')\n",
"for k, v in timings.items():\n",
"    print(f'  {k}: {v}')\n",
]),

code([
"# Optional: WebSocket server for browser client\n",
"# Uncomment and run to start real-time streaming server\n",
"# Expose port 8765 in RunPod pod settings\n",
"\n",
"# import asyncio, nest_asyncio\n",
"# nest_asyncio.apply()\n",
"# from unified_pipeline.async_pipeline import StreamingPipelineServer\n",
"# server = StreamingPipelineServer(unified)\n",
"# print('Starting WebSocket server on :8765')\n",
"# asyncio.get_event_loop().run_until_complete(server.serve('0.0.0.0', 8765))\n",
"\n",
"print('WebSocket server: uncomment above to enable')\n",
]),

code([
"# Cleanup GPU memory\n",
"import gc, torch\n",
"del models, unified\n",
"gc.collect()\n",
"torch.cuda.empty_cache()\n",
"alloc = torch.cuda.memory_allocated() / 1e9\n",
"print(f'VRAM after cleanup: {alloc:.2f} GB allocated')\n",
]),

]

nb = {
    "nbformat": 4,
    "nbformat_minor": 5,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"},
    },
    "cells": cells,
}

out = pathlib.Path(r"e:\LAB\codeV2\Moshi-AvatarForcing-bridge\unified_runpod_inference.ipynb")
with open(out, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
print("Written:", out)
print("Cells:", len(cells))
